plugins {
    id 'com.android.application' version '8.5.0' apply false
    id 'org.jetbrains.kotlin.android' version '2.0.21' apply false
    id 'org.jetbrains.kotlin.kapt' version '2.0.21' apply false
    id 'com.google.dagger.hilt.android' version '2.51' apply false
}

tasks.register('assemble') {
    group = 'build'
    description = '从根项目构建 app 模块。'
    dependsOn ':app:assemble'
}
