package kt.constants

object EnvNames {
    const val REGION_ID = "MAIMAI_REGION_ID"
    const val REGION_NAME = "MAIMAI_REGION_NAME"
    const val PLACE_ID = "MAIMAI_PLACE_ID"
    const val PLACE_NAME = "MAIMAI_PLACE_NAME"
    const val CLIENT_ID = "MAIMAI_CLIENT_ID"
    const val TITLE_ENDPOINT = "MAIMAI_TITLE_ENDPOINT"
    const val AIME_ENDPOINT = "MAIMAI_AIME_ENDPOINT"
    const val AIME_COMMON_KEY = "MAIMAI_AIME_COMMON_KEY"
    const val CHIP_ID = "MAIMAI_CHIP_ID"
    const val TITLE_TIMEOUT_MILLIS = "MAIMAI_TITLE_TIMEOUT_MILLIS"
    const val MAX_RETRIES = "MAIMAI_MAX_RETRIES"
    const val VERIFY_TLS = "MAIMAI_VERIFY_TLS"
    const val USE_2024_API = "MAIMAI_USE_2024_API"
    const val WAIT_BEFORE_UPSERT_MILLIS = "MAIMAI_WAIT_BEFORE_UPSERT_MILLIS"
    const val MUSIC_DB_PATH = "MAIMAI_MUSIC_DB_PATH"
}

object DefaultValues {
    const val REGION_ID = 3
    const val REGION_NAME = "Shanghai"
    const val PLACE_ID = 1187
    const val PLACE_NAME = ""
    const val CLIENT_ID = "A63E01C2588"
    const val TITLE_ENDPOINT = "https://maimai-gm.wahlap.com:42081/Maimai2Servlet/"
    const val AIME_ENDPOINT = "http://ai.sys-allnet.cn/wc_aime/api/get_data"
    const val AIME_COMMON_KEY = "XcW5FW4cPArBXEk4vzKz3CIrMuA5EVVW"
    const val CHIP_ID = ""
    const val TITLE_TIMEOUT_MILLIS = 10_000L
    const val MAX_RETRIES = 3
    const val VERIFY_TLS = false
    const val USE_2024_API = false
    const val WAIT_BEFORE_UPSERT_MILLIS = 60_000L
    const val MUSIC_DB_PATH = "../Data/musicDB.json"
}

object CryptoConstants {
    const val AES_KEY_2024 = "n7bx6:@Fg_:2;5E89Phy7AyIcpxEQ:R@"
    const val AES_KEY_LEGACY = "o2U8F6<adcYl25f_qwx_n]5_qxRcbLN>"
    const val AES_IV_2024 = ";;KjR1C3hgB1ovXa"
    const val AES_IV_LEGACY = "AL<G:k:X6Vu7@_U]"
    const val OBFUSCATE_2024 = "BEs2D5vW"
    const val OBFUSCATE_LEGACY = "LatuAa81"
}

object ApiNames {
    const val USER_LOGIN = "UserLoginApi"
    const val USER_LOGOUT = "UserLogoutApi"
    const val GET_USER_PREFIX = "GetUser"
    const val API_SUFFIX = "Api"
    const val GET_USER_PREVIEW = "GetUserPreviewApi"
    const val GET_USER_MUSIC = "GetUserMusicApi"
    const val UPSERT_USER_ALL = "UpsertUserAllApi"
    const val UPSERT_CHARGE_LOG = "UpsertUserChargelogApi"
}

object PayloadKeys {
    const val COOKIE = "_cookie"
    const val USER_ID = "userId"
    const val AIME_USER_ID = "userID"
    const val USER_DATA = "userData"
    const val USER_CHARGE = "userCharge"
    const val USER_CHARGE_LIST = "userChargeList"
    const val USER_CHARGE_LOG = "userChargelog"
    const val USER_MUSIC_DETAIL_LIST = "userMusicDetailList"
    const val UPSERT_USER_ALL = "upsertUserAll"
    const val IS_NEW_MUSIC_DETAIL_LIST = "isNewMusicDetailList"
    const val ACCESS_CODE = "accessCode"
    const val REGION_ID = "regionId"
    const val PLACE_ID = "placeId"
    const val PLACE_NAME = "placeName"
    const val CLIENT_ID = "clientId"
    const val DATE_TIME = "dateTime"
    const val IS_CONTINUE = "isContinue"
    const val GENERIC_FLAG = "genericFlag"
    const val TOKEN = "token"
    const val TYPE = "type"
    const val SEGA_ID_AUTH_KEY = "segaIdAuthKey"
    const val NEXT_INDEX = "nextIndex"
    const val MAX_COUNT = "maxCount"
    const val RETURN_CODE = "returnCode"
    const val RESULT_CODE = "resultCode"
    const val STATUS = "status"
    const val CODE = "code"
    const val CHIP_ID = "chipID"
    const val OPEN_GAME_ID = "openGameID"
    const val KEY = "key"
    const val QR_CODE = "qrCode"
    const val TIMESTAMP = "timestamp"
    const val CHARGE_ID = "chargeId"
    const val PRICE = "price"
    const val PURCHASE_DATE = "purchaseDate"
    const val PLAY_COUNT = "playCount"
    const val PLAYER_RATING = "playerRating"
    const val STOCK = "stock"
    const val VALID_DATE = "validDate"
    const val MUSIC_ID = "musicId"
    const val LEVEL = "level"
    const val LAST_ROM_VERSION = "lastRomVersion"
    const val LAST_DATA_VERSION = "lastDataVersion"
    const val USER_ITEM_LIST = "userItemList"
    const val IS_NEW_ITEM_LIST = "isNewItemList"
    const val ITEM_KIND = "itemKind"
    const val ITEM_ID = "itemId"
    const val IS_VALID = "isValid"
    const val LOGIN_ID = "loginId"
    const val PLAYLOG_ID = "playlogId"
    const val IS_EVENT_MODE = "isEventMode"
    const val IS_FREE_PLAY = "isFreePlay"
    const val USER_PLAYLOG_LIST = "userPlaylogList"
    const val USER_EXTEND = "userExtend"
    const val USER_OPTION = "userOption"
    const val USER_GHOST = "userGhost"
    const val USER_CHARACTER_LIST = "userCharacterList"
    const val CHARACTER_ID = "characterId"
    const val AWAKENING = "awakening"
    const val USE_COUNT = "useCount"
    const val USER_MAP_LIST = "userMapList"
    const val USER_LOGIN_BONUS_LIST = "userLoginBonusList"
    const val USER_RATING = "userRating"
    const val USER_RATING_LIST = "userRatingList"
    const val USER_COURSE_LIST = "userCourseList"
    const val USER_FRIEND_SEASON_RANKING_LIST = "userFriendSeasonRankingList"
    const val USER_FAVORITE_LIST = "userFavoriteList"
    const val USER_ACTIVITY = "userActivity"
    const val USER_ACTIVITY_LIST = "userActivityList"
    const val USER_MISSION_DATA_LIST = "userMissionDataList"
    const val USER_WEEKLY_DATA = "userWeeklyData"
    const val USER_GAME_PLAYLOG_LIST = "userGamePlaylogList"
    const val VERSION = "version"
    const val PLAY_DATE = "playDate"
    const val PLAY_MODE = "playMode"
    const val USE_TICKET_ID = "useTicketId"
    const val PLAY_CREDIT = "playCredit"
    const val PLAY_TRACK = "playTrack"
    const val IS_PLAY_TUTORIAL = "isPlayTutorial"
    const val IS_NEW_FREE = "isNewFree"
    const val PLAY_SPECIAL = "playSpecial"
    const val PLAY_OTHER_USER_ID = "playOtherUserId"
    const val USER_2P_PLAYLOG = "user2pPlaylog"
    const val USER_ID_1 = "userId1"
    const val USER_ID_2 = "userId2"
    const val USER_NAME_1 = "userName1"
    const val USER_NAME_2 = "userName2"
    const val USER_2P_PLAYLOG_DETAIL_LIST = "user2pPlaylogDetailList"
    const val USER_INTIMATE_LIST = "userIntimateList"
    const val USER_SHOP_ITEM_STOCK_LIST = "userShopItemStockList"
    const val USER_GET_POINT_LIST = "userGetPointList"
    const val USER_TRADE_ITEM_LIST = "userTradeItemList"
    const val USER_FAVORITE_MUSIC_LIST = "userFavoritemusicList"
    const val USER_KALEIDX_SCOPE_LIST = "userKaleidxScopeList"
    const val IS_NEW_CHARACTER_LIST = "isNewCharacterList"
    const val IS_NEW_MAP_LIST = "isNewMapList"
    const val IS_NEW_LOGIN_BONUS_LIST = "isNewLoginBonusList"
    const val IS_NEW_COURSE_LIST = "isNewCourseList"
    const val IS_NEW_FAVORITE_LIST = "isNewFavoriteList"
    const val IS_NEW_FRIEND_SEASON_RANKING_LIST = "isNewFriendSeasonRankingList"
    const val IS_NEW_USER_INTIMATE_LIST = "isNewUserIntimateList"
    const val IS_NEW_FAVORITE_MUSIC_LIST = "isNewFavoritemusicList"
    const val IS_NEW_KALEIDX_SCOPE_LIST = "isNewKaleidxScopeList"
    const val CHARA_LOCK_SLOT = "charaLockSlot"
    const val CHARA_SLOT = "charaSlot"
    const val CLASS_RANK = "classRank"
    const val CM_LAST_EMONEY_BRAND = "cmLastEmoneyBrand"
    const val CM_LAST_EMONEY_CREDIT = "cmLastEmoneyCredit"
    const val POINT = "point"
    const val TOTAL_POINT = "totalPoint"
    const val COMPATIBLE_CM_VERSION = "compatibleCmVersion"
    const val CONTENT_BIT = "contentBit"
    const val COURSE_RANK = "courseRank"
    const val CURRENT_PLAY_COUNT = "currentPlayCount"
    const val DAILY_BONUS_DATE = "dailyBonusDate"
    const val DAILY_COURSE_BONUS_DATE = "dailyCourseBonusDate"
    const val EVENT_WATCHED_DATE = "eventWatchedDate"
    const val FIRST_DATA_VERSION = "firstDataVersion"
    const val FIRST_PLAY_DATE = "firstPlayDate"
    const val FIRST_ROM_VERSION = "firstRomVersion"
    const val FRAME_ID = "frameId"
    const val FRIEND_CODE = "friendCode"
    const val FRIEND_REGIST_SKIP = "friendRegistSkip"
    const val GRADE_RANK = "gradeRank"
    const val GRADE_RATING = "gradeRating"
    const val HIGHEST_RATING = "highestRating"
    const val ICON_ID = "iconId"
    const val LAST_LOGIN_DATE = "lastLoginDate"
    const val LAST_PAIR_LOGIN_DATE = "lastPairLoginDate"
    const val LAST_SELECT_COURSE = "lastSelectCourse"
    const val LAST_TRIAL_PLAY_DATE = "lastTrialPlayDate"
    const val MAP_STOCK = "mapStock"
    const val MUSIC_RATING = "musicRating"
    const val NAMEPLATE_ID = "nameplateId"
    const val PARTNER_ID = "partnerId"
    const val PLATE_ID = "plateId"
    const val PLAYER_NEW_RATING = "playerNewRating"
    const val PLAYER_OLD_RATING = "playerOldRating"
    const val SELECT_MAP_ID = "selectMapId"
    const val TITLE_ID = "titleId"
    const val TOTAL_ACHIEVEMENT = "totalAchievement"
    const val TOTAL_ADVANCED_ACHIEVEMENT = "totalAdvancedAchievement"
    const val TOTAL_ADVANCED_DELUXSCORE = "totalAdvancedDeluxscore"
    const val TOTAL_ADVANCED_SYNC = "totalAdvancedSync"
    const val TOTAL_AWAKE = "totalAwake"
    const val TOTAL_BASIC_ACHIEVEMENT = "totalBasicAchievement"
    const val TOTAL_BASIC_DELUXSCORE = "totalBasicDeluxscore"
    const val TOTAL_BASIC_SYNC = "totalBasicSync"
    const val TOTAL_DELUXSCORE = "totalDeluxscore"
    const val TOTAL_EXPERT_ACHIEVEMENT = "totalExpertAchievement"
    const val TOTAL_EXPERT_DELUXSCORE = "totalExpertDeluxscore"
    const val TOTAL_EXPERT_SYNC = "totalExpertSync"
    const val TOTAL_MASTER_ACHIEVEMENT = "totalMasterAchievement"
    const val TOTAL_MASTER_DELUXSCORE = "totalMasterDeluxscore"
    const val TOTAL_MASTER_SYNC = "totalMasterSync"
    const val TOTAL_REMASTER_ACHIEVEMENT = "totalReMasterAchievement"
    const val TOTAL_REMASTER_DELUXSCORE = "totalReMasterDeluxscore"
    const val TOTAL_REMASTER_SYNC = "totalReMasterSync"
    const val TOTAL_SYNC = "totalSync"
    const val TROPHY_ID = "trophyId"
    const val USER_NAME = "userName"
    const val COMBO_COUNT = "comboCount"
    const val FIRST_GAME_ID = "firstGameId"
    const val HELP_COUNT = "helpCount"
    const val IS_NET_MEMBER = "isNetMember"
    const val LAST_ALL_NET_ID = "lastAllNetId"
    const val LAST_CLIENT_ID = "lastClientId"
    const val LAST_COUNT_COURSE = "lastCountCourse"
    const val LAST_COUNTRY_CODE = "lastCountryCode"
    const val LAST_GAME_ID = "lastGameId"
    const val LAST_PLACE_ID = "lastPlaceId"
    const val LAST_PLACE_NAME = "lastPlaceName"
    const val LAST_PLAY_CREDIT = "lastPlayCredit"
    const val LAST_PLAY_DATE = "lastPlayDate"
    const val LAST_PLAY_MODE = "lastPlayMode"
    const val LAST_REGION_ID = "lastRegionId"
    const val LAST_REGION_NAME = "lastRegionName"
    const val LAST_SELECT_EMONEY = "lastSelectEMoney"
    const val LAST_SELECT_TICKET = "lastSelectTicket"
    const val PLAY_SYNC_COUNT = "playSyncCount"
    const val PLAY_VS_COUNT = "playVsCount"
    const val RENAME_CREDIT = "renameCredit"
    const val WIN_COUNT = "winCount"
    const val ORDER_ID = "orderId"
    const val LOGIN_DATE = "loginDate"
    const val USER_PLAY_DATE = "userPlayDate"
    const val TRACK_NO = "trackNo"
    const val VS_MODE = "vsMode"
    const val VS_USER_NAME = "vsUserName"
    const val VS_STATUS = "vsStatus"
    const val VS_USER_RATING = "vsUserRating"
    const val VS_USER_ACHIEVEMENT = "vsUserAchievement"
    const val VS_USER_GRADE_RANK = "vsUserGradeRank"
    const val VS_RANK = "vsRank"
    const val PLAYER_NUM = "playerNum"
    const val PLAYED_USER_ID_1 = "playedUserId1"
    const val PLAYED_USER_NAME_1 = "playedUserName1"
    const val PLAYED_MUSIC_LEVEL_1 = "playedMusicLevel1"
    const val PLAYED_USER_ID_2 = "playedUserId2"
    const val PLAYED_USER_NAME_2 = "playedUserName2"
    const val PLAYED_MUSIC_LEVEL_2 = "playedMusicLevel2"
    const val PLAYED_USER_ID_3 = "playedUserId3"
    const val PLAYED_USER_NAME_3 = "playedUserName3"
    const val PLAYED_MUSIC_LEVEL_3 = "playedMusicLevel3"
    const val CHARACTER_ID_1 = "characterId1"
    const val CHARACTER_LEVEL_1 = "characterLevel1"
    const val CHARACTER_AWAKENING_1 = "characterAwakening1"
    const val CHARACTER_ID_2 = "characterId2"
    const val CHARACTER_LEVEL_2 = "characterLevel2"
    const val CHARACTER_AWAKENING_2 = "characterAwakening2"
    const val CHARACTER_ID_3 = "characterId3"
    const val CHARACTER_LEVEL_3 = "characterLevel3"
    const val CHARACTER_AWAKENING_3 = "characterAwakening3"
    const val CHARACTER_ID_4 = "characterId4"
    const val CHARACTER_LEVEL_4 = "characterLevel4"
    const val CHARACTER_AWAKENING_4 = "characterAwakening4"
    const val CHARACTER_ID_5 = "characterId5"
    const val CHARACTER_LEVEL_5 = "characterLevel5"
    const val CHARACTER_AWAKENING_5 = "characterAwakening5"
    const val DELUXSCORE = "deluxscore"
    const val DELUXSCORE_MAX = "deluxscoreMax"
    const val ACHIEVEMENT = "achievement"
    const val SCORE_RANK = "scoreRank"
    const val MAX_COMBO = "maxCombo"
    const val TOTAL_COMBO = "totalCombo"
    const val MAX_SYNC = "maxSync"

    const val TAP_CRITICAL_PERFECT = "tapCriticalPerfect"
    const val TAP_PERFECT = "tapPerfect"
    const val TAP_GREAT = "tapGreat"
    const val TAP_GOOD = "tapGood"
    const val TAP_MISS = "tapMiss"
    const val HOLD_CRITICAL_PERFECT = "holdCriticalPerfect"
    const val HOLD_PERFECT = "holdPerfect"
    const val HOLD_GREAT = "holdGreat"
    const val HOLD_GOOD = "holdGood"
    const val HOLD_MISS = "holdMiss"
    const val SLIDE_CRITICAL_PERFECT = "slideCriticalPerfect"
    const val SLIDE_PERFECT = "slidePerfect"
    const val SLIDE_GREAT = "slideGreat"
    const val SLIDE_GOOD = "slideGood"
    const val SLIDE_MISS = "slideMiss"
    const val TOUCH_CRITICAL_PERFECT = "touchCriticalPerfect"
    const val TOUCH_PERFECT = "touchPerfect"
    const val TOUCH_GREAT = "touchGreat"
    const val TOUCH_GOOD = "touchGood"
    const val TOUCH_MISS = "touchMiss"
    const val BREAK_CRITICAL_PERFECT = "breakCriticalPerfect"
    const val BREAK_PERFECT = "breakPerfect"
    const val BREAK_GREAT = "breakGreat"
    const val BREAK_GOOD = "breakGood"
    const val BREAK_MISS = "breakMiss"
    const val IS_TAP = "isTap"
    const val IS_HOLD = "isHold"
    const val IS_SLIDE = "isSlide"
    const val IS_TOUCH = "isTouch"
    const val IS_BREAK = "isBreak"
    const val IS_CRITICAL_DISP = "isCriticalDisp"
    const val IS_FAST_LATE_DISP = "isFastLateDisp"
    const val FAST_COUNT = "fastCount"
    const val LATE_COUNT = "lateCount"
    const val IS_ACHIEVE_NEW_RECORD = "isAchieveNewRecord"
    const val IS_DELUXSCORE_NEW_RECORD = "isDeluxscoreNewRecord"
    const val COMBO_STATUS = "comboStatus"
    const val SYNC_STATUS = "syncStatus"
    const val IS_CLEAR = "isClear"
    const val BEFORE_RATING = "beforeRating"
    const val AFTER_RATING = "afterRating"
    const val BEFORE_GRADE = "beforeGrade"
    const val AFTER_GRADE = "afterGrade"
    const val AFTER_GRADE_RANK = "afterGradeRank"
    const val BEFORE_DELUX_RATING = "beforeDeluxRating"
    const val AFTER_DELUX_RATING = "afterDeluxRating"
    const val IS_FREEDOM_MODE = "isFreedomMode"
    const val TRIAL_PLAY_ACHIEVEMENT = "trialPlayAchievement"
    const val EXT_NUM_1 = "extNum1"
    const val EXT_NUM_2 = "extNum2"
    const val EXT_NUM_4 = "extNum4"
    const val EXT_BOOL_1 = "extBool1"
    const val EXT_BOOL_2 = "extBool2"
}

object PayloadDefaults {
    const val EMPTY = ""
    const val ZERO_STRING = "0"
    const val DATE_TIME_FRACTION_SUFFIX = ".0"
    const val GAME_ID = "SDGB"
    const val COUNTRY_CODE = "CHN"
    const val GAME_PLAYLOG_VERSION = "1.53.00"
    const val PLAYLOG_VERSION = 1_053_000
}

object VersionDefaults {
    const val ROM_VERSION = "1.50.00"
    const val DATA_VERSION = "1.50.01"
}

object UserDataKinds {
    const val DATA = "Data"
    const val EXTEND = "Extend"
    const val OPTION = "Option"
    const val RATING = "Rating"
    const val ACTIVITY = "Activity"
    const val CHARGE = "Charge"
    const val MISSION_DATA = "MissionData"
}

object AimeConstants {
    const val OPEN_GAME_ID_MAID = "MAID"
    const val USER_AGENT = "WC_AIME_LIB"
    const val SGWC_PREFIX = "SGWCMAID"
    const val QR_PAYLOAD_LENGTH = 64
    const val SGWC_LENGTH = 84
    const val HEX_PATTERN = "^[0-9A-F]+$"
}

object HttpConstants {
    const val CONNECTION = "Connection"
    const val KEEP_ALIVE = "Keep-Alive"
    const val HOST = "Host"
    const val USER_AGENT = "User-Agent"
    const val CONTENT_TYPE = "Content-Type"
    const val APPLICATION_JSON = "application/json"
    const val MAI_ENCODING = "Mai-Encoding"
    const val MAI_ENCODING_VALUE = "1.53"
    const val ACCEPT_ENCODING = "Accept-Encoding"
    const val CHARSET = "Charset"
    const val UTF_8 = "UTF-8"
    const val CONTENT_ENCODING = "Content-Encoding"
    const val DEFLATE = "deflate"
    const val TITLE_HOST = "maimai-gm.wahlap.com:42081"
    const val TITLE_USER_AGENT_SEPARATOR = "#"
    const val COOKIE_SEPARATOR = ";"
    const val KEY_VALUE_SEPARATOR = "="
    const val TLS = "TLS"
}

object LoginCodes {
    const val SUCCESS = 1
    const val PLAYING = 100
    const val QR_REFRESH_REQUIRED = 102
}

object DatePatterns {
    const val AIME_TIMESTAMP = "yyMMddHHmmss"
    const val DATE_TIME = "yyyy-MM-dd HH:mm:ss"
}

object ZoneIds {
    const val TOKYO = "Asia/Tokyo"
    const val SHANGHAI = "Asia/Shanghai"
}
